name: CI
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: checkout code
              uses: actions/checkout@v3

            - name: setup python
              uses: actions/setup-python@v4
              with:
                  python-version: '3.10'
            - name: install dependencies
              run: pip install pytest

            - name: run tests
              run: pytest -q tests/

            - name: Show secret usage
              run: echo "Secret key is ${{ secrets.MY_SECRET_KEY }}"
              
            - name: Run Python script with secret
              run: 
                python -c "import calculator; print(calculator.get_secret_value())"
              env:
                MY_SECRET_KEY: ${{ secrets.MY_SECRET_KEY }}

    test:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                python_version: ['3.8', '3.9','3.10']


        steps:
            - name: checkout code
              uses: actions/checkout@v3

            - name: setup python
              uses: actions/setup-python@v4
              with:
                  python-version: '3.10'
            - name: install dependencies
              run: |
                python -m pip install --upgrade pip
                if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
                pip install pytest

            - name: run tests
              run: pytest -q
