name: CI
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: checkout code
              uses: actions/checkout@v3

            - name: setup python
              uses: actions/setup-python@v4
              with:
                  python-version: '3.10'
            - name: install dependencies
              run: |
                python -m pip install --upgrade pip
                if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

            - name: run tests
              run: |
                pytest || echo "No tests yet"

            - name: Debug environment
              run: |
                python --version
                pip list
                env
            - name: Upload test results
              if: always()
              uses: actions/upload-artifact@v4
              with:
                name: pytest-report
                path: tests/reports/
